SkillsFundingAgency/das-findapprenticeship-web

src/SFA.DAS.FAA.Application/Queries/Apply/GetApplicationSubmitted/GetApplicationSubmittedQuery.cs, src/SFA.DAS.FAA.Application/Queries/Apply/GetApplicationSubmitted/GetApplicationSubmittedQueryHandler.cs, src/SFA.DAS.FAA.Application/Queries/Apply/GetApplicationSubmitted/GetApplicationSubmittedQueryResponse.cs, src/SFA.DAS.FAA.ApplicationUnitTests/Queries/Apply/WhenHandlingGetApplicationSubmittedQuery.cs, src/SFA.DAS.FAA.Domain/Apply/GetApplicationSubmitted/GetApplicationSubmittedApiRequest.cs, src/SFA.DAS.FAA.Domain/Apply/GetApplicationSubmitted/GetApplicationSubmittedApiResponse.cs, src/SFA.DAS.FAA.DomainUnitTests/Apply/ApplicationSubmitted/WhenBuildingApplicationSubmittedApiRequest.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/WhenGettingApplicationSubmitted.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/WhenPostingApplicationSubmitted.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/WhenPostingIndex.cs, src/SFA.DAS.FAA.Web.UnitTests/Validators/WhenValidatingApplicationSubmittedViewModel.cs, src/SFA.DAS.FAA.Web/Controllers/ApplyController.cs, src/SFA.DAS.FAA.Web/Infrastructure/RouteNames.cs, src/SFA.DAS.FAA.Web/Models/Apply/ApplicationSubmittedViewModel.cs, src/SFA.DAS.FAA.Web/Validators/ApplicationSubmittedViewModelValidator.cs, src/SFA.DAS.FAA.Web/Views/Apply/ApplicationSubmitted.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/Index.cshtml
Adds the **application submitted success page** with equality question radio, and **validation** for the radio
=> FAI-1124 Add application submitted success page

src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/WhenGettingApplicationSubmittedConfirmation.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/WhenPostingApplicationSubmitted.cs, src/SFA.DAS.FAA.Web.UnitTests/Models/Apply/WhenMappingMediatrResponseToApplicationSubmittedConfirmationViewModel.cs, src/SFA.DAS.FAA.Web.UnitTests/Validators/WhenValidatingApplicationSubmittedViewModel.cs, src/SFA.DAS.FAA.Web/Controllers/ApplyController.cs, src/SFA.DAS.FAA.Web/Infrastructure/RouteNames.cs, src/SFA.DAS.FAA.Web/Models/Apply/ApplicationSubmittedConfirmationViewModel.cs, src/SFA.DAS.FAA.Web/Models/Apply/ApplicationSubmittedVacancyInfo.cs, src/SFA.DAS.FAA.Web/Models/Apply/ApplicationSubmittedViewModel.cs, src/SFA.DAS.FAA.Web/Views/Apply/ApplicationSubmitted.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/ApplicationSubmittedConfirmation.cshtml, src/SFA.DAS.FAA.Web/Views/Shared/_ApplicationSubmittedPartial.cshtml
Story: https://skillsfundingagency.atlassian.net/browse/FAI-1119
=> FAI-1119 Application Submitted Confirmation Page

src/SFA.DAS.FAA.Domain/Enums/GenderIdentity.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/EqualityQuestions/WhenCallingGetEqualityGender.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/EqualityQuestions/WhenCallingPostEqualityGender.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/WhenPostingApplicationSubmitted.cs, src/SFA.DAS.FAA.Web.UnitTests/Infrastructure/WhenUsingCacheStorageService.cs, src/SFA.DAS.FAA.Web.UnitTests/Models/Apply/WhenMappingEqualityQuestionViewModel.cs, src/SFA.DAS.FAA.Web.UnitTests/Validators/EqualityQuestionsGenderViewModelValidatorTest.cs, src/SFA.DAS.FAA.Web/AppStart/AddServiceRegistrationExtensions.cs, src/SFA.DAS.FAA.Web/Controllers/Apply/EqualityQuestionsController.cs, src/SFA.DAS.FAA.Web/Controllers/ApplyController.cs, src/SFA.DAS.FAA.Web/Infrastructure/CacheKeys.cs, src/SFA.DAS.FAA.Web/Infrastructure/CacheStorageService.cs, src/SFA.DAS.FAA.Web/Infrastructure/RouteNames.cs, src/SFA.DAS.FAA.Web/Models/Apply/EqualityGenderViewModel.cs, src/SFA.DAS.FAA.Web/Models/Apply/EqualityQuestionsGenderViewModel.cs, src/SFA.DAS.FAA.Web/Models/Apply/EqualityQuestionsModel.cs, src/SFA.DAS.FAA.Web/Program.cs, src/SFA.DAS.FAA.Web/Validators/EqualityGenderViewModelValidator.cs, src/SFA.DAS.FAA.Web/Views/Apply/EqualityQuestions/Gender.cshtml
Introduced InMemoryCache to store the Equality Page Answers with DataProtector to secure the CacheKey
Story: https://skillsfundingagency.atlassian.net/browse/FAI-1120
=> FAI-1120 Equality Questions Controller added with Gender Page

src/SFA.DAS.FAA.Application/Queries/Apply/GetApplicationSummary/GetApplicationSummaryQueryResult.cs, src/SFA.DAS.FAA.Application/Queries/Apply/GetQualifications/GetQualificationsQuery.cs, src/SFA.DAS.FAA.Domain/Apply/GetApplicationSummary/GetApplicationSummaryApiResponse.cs, src/SFA.DAS.FAA.Domain/Apply/Qualifications/GetQualificationsApiRequest.cs, src/SFA.DAS.FAA.Web.UnitTests/Models/Apply/WhenMappingGetApplicationSummaryQueryResultToModel.cs, src/SFA.DAS.FAA.Web/Models/Apply/ApplicationSummaryViewModel.cs, src/SFA.DAS.FAA.Web/Models/Apply/QualificationsViewModel.cs, src/SFA.DAS.FAA.Web/Views/Apply/Preview.cshtml
Added Education Qualifications details to the Application Preview page + Clean up
Story: https://skillsfundingagency.atlassian.net/browse/FAI-1156
=> Fai-1191 Add education details application preview

src/SFA.DAS.FAA.Application/Queries/Applications/GetIndex/GetIndexQueryResult.cs, src/SFA.DAS.FAA.Domain/Applications/GetApplications/GetApplicationsApiResponse.cs, src/SFA.DAS.FAA.Web/Controllers/ApplicationsController.cs, src/SFA.DAS.FAA.Web/Models/Applications/IndexViewModel.cs, src/SFA.DAS.FAA.Web/Views/Applications/Index.cshtml, src/SFA.DAS.FAA.Web/Views/Applications/_Application.cshtml, src/SFA.DAS.FAA.Web/Views/Applications/_SubmittedApplication.cshtml
Story: https://skillsfundingagency.atlassian.net/browse/FAI-1201
=> FAI-1201 Added Application Submitted tab to the My Applications area

src/SFA.DAS.FAA.Web.UnitTests/Controllers/SearchApprenticeshipsControllerTests/WhenGettingIndex.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/SearchApprenticeshipsControllerTests/WhenGettingSearchResults.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Vacancies/WhenGettingVacancyDetails.cs, src/SFA.DAS.FAA.Web.UnitTests/Services/NotificationBannerServiceTest.cs, src/SFA.DAS.FAA.Web/Controllers/SearchApprenticeshipsController.cs, src/SFA.DAS.FAA.Web/Controllers/UserController.cs, src/SFA.DAS.FAA.Web/Controllers/VacanciesController.cs, src/SFA.DAS.FAA.Web/Infrastructure/CacheKeys.cs, src/SFA.DAS.FAA.Web/Models/SearchResults/SearchApprenticeshipsViewModel.cs, src/SFA.DAS.FAA.Web/Models/SearchResults/SearchResultsViewModel.cs, src/SFA.DAS.FAA.Web/Models/Vacancy/VacancyDetailsViewModel.cs, src/SFA.DAS.FAA.Web/Services/NotificationBannerService.cs, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/Index.cshtml, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/SearchResults.cshtml, src/SFA.DAS.FAA.Web/Views/Shared/_AccountCreatedBanner.cshtml, src/SFA.DAS.FAA.Web/Views/Vacancies/Vacancy.cshtml
Added New Account Creation Banner message to Search Results, Home & Vacancy Details Page
Story: https://skillsfundingagency.atlassian.net/browse/FAI-1247
=> FAI-1247 Added New Account Creation Banner

src/SFA.DAS.FAA.Web/Frontend/scss/components/vacancy/_index.scss, src/SFA.DAS.FAA.Web/Views/Applications/_ExpiredApplication.cshtml, src/SFA.DAS.FAA.Web/Views/Applications/_StartedApplication.cshtml, src/SFA.DAS.FAA.Web/Views/Applications/_SubmittedApplication.cshtml, src/SFA.DAS.FAA.Web/Views/Applications/_SuccessfulApplication.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/DisabilityConfident/Summary.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/InterviewAdjustments/Summary.cshtml
- removed some css classes on list items on application tabs
- small accessibility fixon radio buttons
=> FAIR-1249 CSS fix for print and favourite icons

src/SFA.DAS.FAA.Web.AcceptanceTests/Data/Pages.cs, src/SFA.DAS.FAA.Web.AcceptanceTests/Features/CreateAccount/GetChangeEmail.feature, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Users/WhenGettingEmail.cs, src/SFA.DAS.FAA.Web/Controllers/UserController.cs, src/SFA.DAS.FAA.Web/Infrastructure/RouteNames.cs, src/SFA.DAS.FAA.Web/Models/User/EmailViewModel.cs, src/SFA.DAS.FAA.Web/Views/User/CheckAnswers.cshtml, src/SFA.DAS.FAA.Web/Views/User/Email.cshtml
Story: https://skillsfundingagency.atlassian.net/browse/FAI-1316
=> Change email page added with unit and acceptance test cases.

src/SFA.DAS.FAA.Web/Views/Shared/_Layout.cshtml
https://skillsfundingagency.atlassian.net/browse/FAI-1716
=> FAI-1716 Footer Feedback link added to the layout

src/SFA.DAS.FAA.Web.UnitTests/Validators/WhenValidatingNameViewModel.cs, src/SFA.DAS.FAA.Web/Models/User/NameViewModel.cs, src/SFA.DAS.FAA.Web/Validators/NameViewModelValidator.cs, src/SFA.DAS.FAA.Web/Views/User/Name.cshtml
Adding NameViewModel Validator Message
Bug: https://skillsfundingagency.atlassian.net/browse/FAI-1752
=> FAI-1752 Adding Name Validation Message

src/SFA.DAS.FAA.Web/Controllers/SearchApprenticeshipsController.cs, src/SFA.DAS.FAA.Web/Program.cs, src/SFA.DAS.FAA.Web/Views/Shared/_Layout.cshtml
https://skillsfundingagency.atlassian.net/browse/FAI-1769
=> FAI-1769 Footer links removing _blank tags

src/SFA.DAS.FAA.Web.UnitTests/Filters/WhenFilteringNewAccountUsers.cs, src/SFA.DAS.FAA.Web/Controllers/HomeController.cs, src/SFA.DAS.FAA.Web/Filters/NewFaaUserAccountFilter.cs, src/SFA.DAS.FAA.Web/Views/User/CreateAccount.cshtml
Commit Details:
1. Added the links for the Terms & Privacy Policy
2. Excluding HomeController from the NewFAAUserAccountFilter 
Story: https://skillsfundingagency.atlassian.net/browse/FAI-1756
=> FAI-1756 Added the links for the Terms & Privacy Policy

src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/VolunteeringAndWorkExperience/WhenPostingAddVolunteeringAndWorkExperiencePage.cs, src/SFA.DAS.FAA.Web.UnitTests/Validators/WhenValidatingSubjectViewModel.cs, src/SFA.DAS.FAA.Web/Controllers/Apply/VolunteeringAndWorkExperienceController.cs, src/SFA.DAS.FAA.Web/Validators/AddQualificationViewModelValidator.cs
Removed the validator for Degree dropdown textbox as it is a dropdown list doesn't require ValidFreeTextCharacters.
Pre-selected Volunteering & Work Experiences radio button snags removed
Bug: https://skillsfundingagency.atlassian.net/browse/FAI-1776
=> FAI-1176 Removed the validator for Degree dropdown textbox

src/SFA.DAS.FAA.Web/Frontend/scss/components/filter/_index.scss
Bug: https://skillsfundingagency.atlassian.net/browse/FAI-1793
=> FAI-1793 Stylings corrected according to the specs

src/SFA.DAS.FAA.Web.UnitTests/Controllers/SearchApprenticeshipsControllerTests/WhenPostingLocations.cs, src/SFA.DAS.FAA.Web.UnitTests/Validators/WhenValidatingLocationViewModel.cs, src/SFA.DAS.FAA.Web/Models/LocationViewModel.cs, src/SFA.DAS.FAA.Web/Validators/LocationViewModelValidator.cs, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/Location.cshtml
Bug: https://skillsfundingagency.atlassian.net/browse/FAI-1795
=> FAI-1795 Browse by interest flow - Error messages broken

src/SFA.DAS.FAA.Web/TagHelpers/DayMonthYearDateTagHelper.cs, src/SFA.DAS.FAA.Web/TagHelpers/MonthYearDateTagHelper.cs, src/SFA.DAS.FAA.Web/Views/Applications/Index.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/DisabilityConfident/Summary.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/EqualityQuestions/EthnicGroup.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/EqualityQuestions/EthnicSubGroupAsian.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/EqualityQuestions/EthnicSubGroupBlack.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/EqualityQuestions/EthnicSubGroupMixed.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/EqualityQuestions/EthnicSubGroupOther.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/EqualityQuestions/EthnicSubGroupWhite.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/Index.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/InterviewAdjustments/List.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/InterviewAdjustments/Summary.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/Preview.cshtml, src/SFA.DAS.FAA.Web/Views/Apply/SkillsAndStrengths/List.cshtml, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/Index.cshtml, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/Location.cshtml, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/SearchResults.cshtml, src/SFA.DAS.FAA.Web/Views/Shared/_JobForm.cshtml, src/SFA.DAS.FAA.Web/Views/Shared/_MultiQualification.cshtml, src/SFA.DAS.FAA.Web/Views/Shared/_SingleQualification.cshtml, src/SFA.DAS.FAA.Web/Views/Shared/_TrainingCourseForm.cshtml, src/SFA.DAS.FAA.Web/Views/Shared/_VolunteeringAndWorkExperienceForm.cshtml, src/SFA.DAS.FAA.Web/Views/User/DateOfBirth.cshtml, src/SFA.DAS.FAA.Web/Views/User/EnterAddressManually.cshtml, src/SFA.DAS.FAA.Web/Views/User/Name.cshtml, src/SFA.DAS.FAA.Web/Views/User/PostcodeAddress.cshtml, src/SFA.DAS.FAA.Web/Views/User/SelectAddress.cshtml, src/SFA.DAS.FAA.Web/Views/User/SignInToYourOldAccount.cshtml
- Autocomplete attribute must have a valid value
- ARIA attributes must conform to valid values
- Fieldset must have a legend
- Form label must be associated with a content
- Form field must not have multiple label elements
=> FAI-1765-accessibility-fixes

src/SFA.DAS.FAA.Web.UnitTests/Controllers/Vacancies/WhenGettingVacancyDetails.cs, src/SFA.DAS.FAA.Web/Controllers/VacanciesController.cs
Bug: https://skillsfundingagency.atlassian.net/browse/FAI-1928
=> FAI-1928 Page Back Url to maintain the Search Query

src/SFA.DAS.FAA.Domain/GetApprenticeshipVacancy/GetApprenticeshipVacancyApiResponse.cs, src/SFA.DAS.FAA.Web/Models/Vacancy/VacancyDetailsViewModel.cs, src/SFA.DAS.FAA.Web/Views/Vacancies/_LiveVacancy.cshtml
Add missing application instructions when vacancy is not applied through FAA
=> FAI-1959 - Add missing application instructions

src/SFA.DAS.FAA.Application/Constants/Constants.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/SearchApprenticeshipsControllerTests/WhenGettingSearchResults.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/SearchApprenticeshipsControllerTests/WhenPostingLocations.cs, src/SFA.DAS.FAA.Web/Controllers/SearchApprenticeshipsController.cs, src/SFA.DAS.FAA.Web/Models/SearchResults/GetSearchResultsRequest.cs, src/SFA.DAS.FAA.Web/Models/SearchResults/SearchResultsViewModel.cs, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/SearchResults.cshtml
https://skillsfundingagency.atlassian.net/browse/FAI-1977
=> FAI-1977 Fix for search results page back link

src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/Index.cshtml
Story: https://skillsfundingagency.atlassian.net/browse/FAI-1985
=> FAI-1985 Removed the home page banner

src/SFA.DAS.FAA.Web.UnitTests/Controllers/Users/WhenGettingAccountDeletion.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Users/WhenPostingAccountDeletion.cs, src/SFA.DAS.FAA.Web.UnitTests/Validators/WhenValidatingAccountDeletionViewModel.cs, src/SFA.DAS.FAA.Web/Controllers/UserController.cs, src/SFA.DAS.FAA.Web/Models/User/AccountDeletionViewModel.cs, src/SFA.DAS.FAA.Web/Validators/AccountDeletionViewModelValidator.cs, src/SFA.DAS.FAA.Web/Views/User/AccountDeletion.cshtml, src/SFA.DAS.FAA.Web/Views/User/AccountDeletionWithDrawApplications.cshtml
https://skillsfundingagency.atlassian.net/browse/FAI-1850
=> FAI-1850 Account Deletion Validation Page

src/SFA.DAS.FAA.Web/Views/Apply/Index.cshtml
Story: https://skillsfundingagency.atlassian.net/browse/FAI-1937
=> FAI-1937 Changed the font Color from grey to black

src/SFA.DAS.FAA.Web.UnitTests/Models/WhenMappingVacanciesToMapData.cs
Test was randomly failing due to autodata setup
=> FAI-2052 - fix failing test on main.

src/SFA.DAS.FAA.Web/Views/Shared/_Layout.cshtml, src/SFA.DAS.FAA.Web/wwwroot/css/print.css
Improve print formatting for the vacancy page and the application pages
=> FAI-1995 print styles

src/SFA.DAS.FAA.Application/Queries/GetNhsApprenticeshipVacancy/GetNhsApprenticeshipVacancyQuery.cs, src/SFA.DAS.FAA.Application/Queries/GetNhsApprenticeshipVacancy/GetNhsApprenticeshipVacancyQueryHandler.cs, src/SFA.DAS.FAA.Application/Queries/GetNhsApprenticeshipVacancy/GetNhsApprenticeshipVacancyQueryResult.cs, src/SFA.DAS.FAA.ApplicationUnitTests/Queries/Vacancies/WhenHandlingGetNhsApprenticeshipVacancyQuery.cs, src/SFA.DAS.FAA.Domain/GetNhsApprenticeshipVacancy/GetNhsApprenticeshipVacancyApiRequest.cs, src/SFA.DAS.FAA.Domain/GetNhsApprenticeshipVacancy/GetNhsApprenticeshipVacancyApiResponse.cs, src/SFA.DAS.FAA.Domain/SFA.DAS.FAA.Domain.csproj, src/SFA.DAS.FAA.Domain/SearchResults/GetSearchResultsApiRequest.cs, src/SFA.DAS.FAA.DomainUnitTests/GetNhsApprenticeshipVacancy/WhenBuildingGetNhsApprenticeshipVacancyApiRequest.cs, src/SFA.DAS.FAA.DomainUnitTests/SearchResults/WhenBuildingTheRequest.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/SearchApprenticeshipsControllerTests/WhenGettingSearchResults.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Vacancies/WhenGettingNhsVacancyDetails.cs, src/SFA.DAS.FAA.Web.UnitTests/Services/VacancyDetailsHelperServiceTests.cs, src/SFA.DAS.FAA.Web/Controllers/VacanciesController.cs, src/SFA.DAS.FAA.Web/Infrastructure/RouteNames.cs, src/SFA.DAS.FAA.Web/Models/SearchResults/SearchResultsViewModel.cs, src/SFA.DAS.FAA.Web/Models/VacanciesViewModel.cs, src/SFA.DAS.FAA.Web/Models/Vacancy/NhsVacancyDetailsViewModel.cs, src/SFA.DAS.FAA.Web/Views/SavedSearches/Index.cshtml, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/SearchResults.cshtml, src/SFA.DAS.FAA.Web/Views/Shared/_Layout.cshtml, src/SFA.DAS.FAA.Web/Views/Vacancies/NhsVacancy.cshtml, src/SFA.DAS.FAA.Web/wwwroot/css/print.css
Story: https://skillsfundingagency.atlassian.net/browse/FAI-2023
=> FAI-2023 New Vacancy Details Page for NHS Jobs

src/SFA.DAS.FAA.Application/Queries/GetSearchResults/GetSearchResultsResult.cs, src/SFA.DAS.FAA.Domain/ApiTypeAttribute.cs, src/SFA.DAS.FAA.Domain/GetApprenticeshipVacancy/GetApprenticeshipVacancyApiResponse.cs, src/SFA.DAS.FAA.Domain/SearchResults/GetSearchResultsApiResponse.cs, src/SFA.DAS.FAA.Web.AcceptanceTests/Features/Environment.feature, src/SFA.DAS.FAA.Web.AcceptanceTests/Infrastructure/ContextKeys.cs, src/SFA.DAS.FAA.Web.AcceptanceTests/Infrastructure/TestEnvironmentManagement.cs, src/SFA.DAS.FAA.Web.AcceptanceTests/SFA.DAS.FAA.Web.AcceptanceTests.csproj, src/SFA.DAS.FAA.Web.AcceptanceTests/Steps/ApiContractTests.cs, src/SFA.DAS.FAA.Web/Models/SearchResults/SearchResultsViewModel.cs
Added a basic contract testing mechanisim for checking that a response with attribute on matches the response defined in the open api specification from the outer api
=> FAI-2182 api contract testing

src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/WhenGettingApplicationSubmitted.cs, src/SFA.DAS.FAA.Web/Models/Apply/ApplicationSubmittedViewModel.cs, src/SFA.DAS.FAA.Web/Views/Apply/ApplicationSubmitted.cshtml
Story: https://skillsfundingagency.atlassian.net/browse/FAI-2215
=> FAI-2215 Hotfix for the Page Title in ApplicationSubmitted page

src/SFA.DAS.FAA.Web.UnitTests/Controllers/SearchApprenticeshipsControllerTests/WhenGettingSearchResults.cs, src/SFA.DAS.FAA.Web/Controllers/SearchApprenticeshipsController.cs, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/SearchResults.cshtml
Remove nearest First given the user has not given location in the search criteria
=> FAI-2191 FAI-2263 Remove nearest first option in the Sort by filter

src/SFA.DAS.FAA.Web/Views/Shared/_Layout.cshtml
Added versioning for main.css to avoid the SessionTimeout banner out of sync
=> FAI-2158 Added versioning for main.css file reference

src/SFA.DAS.FAA.Web.UnitTests/Controllers/SearchApprenticeshipsControllerTests/WhenGettingSearchResults.cs, src/SFA.DAS.FAA.Web/Controllers/SearchApprenticeshipsController.cs
remove setting sort based on search params as its causing the sort to not behave how the user has specified
=> FAI-2308 - Remove trying to set sort

src/SFA.DAS.FAA.Application/Queries/Apply/GetDeleteQualifications/GetDeleteQualificationsQueryHandler.cs, src/SFA.DAS.FAA.Application/Queries/Apply/GetDeleteQualifications/GetDeleteQualificationsQueryResult.cs, src/SFA.DAS.FAA.Application/Queries/Apply/GetDeleteTrainingCourse/GetDeleteTrainingCourseQueryHandler.cs, src/SFA.DAS.FAA.Application/Queries/Apply/GetDeleteTrainingCourse/GetDeleteTrainingCourseQueryResult.cs, src/SFA.DAS.FAA.ApplicationUnitTests/Queries/Apply/WhenHandlingGetDeleteQualificationsQuery.cs, src/SFA.DAS.FAA.ApplicationUnitTests/Queries/Apply/WhenHandlingGetDeleteTrainingCourseQuery.cs, src/SFA.DAS.FAA.Domain/Apply/DeleteTrainingCourse/GetDeleteTrainingCourseApiRequest.cs, src/SFA.DAS.FAA.DomainUnitTests/Apply/TrainingCourses/WhenBuildingGetDeleteTrainingCourseApiRequest.cs, src/SFA.DAS.FAA.Web.UnitTests/Controllers/Apply/Qualifications/WhenGettingDeleteQualifications.cs, src/SFA.DAS.FAA.Web/Controllers/Apply/QualificationsController.cs
Handling Not Found response when the Get Delete Qualification Api returns null
=> FAI-2210 Update Back browser button functionality after deleting Qualification

src/SFA.DAS.FAA.Web.UnitTests/Controllers/SearchApprenticeshipsControllerTests/WhenGettingSearchResults.cs, src/SFA.DAS.FAA.Web.UnitTests/Services/FilterBuilderTests.cs, src/SFA.DAS.FAA.Web/Controllers/SearchApprenticeshipsController.cs, src/SFA.DAS.FAA.Web/Models/SearchResults/SearchResultsViewModel.cs, src/SFA.DAS.FAA.Web/Services/FilterBuilder.cs, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/SearchResults.cshtml
Add new filter option for exclude national adverts
=> FAI-2266 add exlude national filter

src/SFA.DAS.FAA.Web/Views/Vacancies/_ClosedVacancyWhenAuthenticated.cshtml
✨ Enhance application status UI and travel directions form
Multiple location Maps changes in Closed Vacancy Authenticated Page
=> FAI-2332 Bug: Missed the Maps display in Closed Vacancy Authenticated View 

src/SFA.DAS.FAA.Web.UnitTests/Controllers/Vacancies/WhenGettingVacancyDetails.cs, src/SFA.DAS.FAA.Web/Controllers/ServiceController.cs, src/SFA.DAS.FAA.Web/Controllers/VacanciesController.cs, src/SFA.DAS.FAA.Web/Views/Vacancies/_LiveVacancy.cshtml
✨ Refactor routing in VacanciesController and tests
- Updated routing attributes in VacanciesController for clarity.
- Modified WhenGettingVacancyDetails tests to use VacanciesController.
- Added tests to verify route order in VacanciesController.
- Adjusted route orders to ensure correct routing precedence.
- Updated form submission routes in _LiveVacancy.cshtml for accuracy.
Changes made by Balaji Jambulingam
=> FAI-2430 Incorrect redirect on apply when not signed in

src/SFA.DAS.FAA.Web/Views/Vacancies/_LiveVacancy.cshtml
✨ Refactor directions map layout in _LiveVacancy.cshtml
- Removed the existing `<div>` for the directions map.
- Added a new `<div>` for the directions map after the journey info.
- Maintained the same class and ID for consistency.
- Improved layout organization for better user experience.
- Adjusted margin-top styling for the new map section.
Changes made by Balaji Jambulingam
=> FAI-2439 Revert the Maps display on Vacancy Details Page

src/SFA.DAS.FAA.Web.UnitTests/Extensions/AccessibilityExtensionsTests.cs, src/SFA.DAS.FAA.Web.UnitTests/Models/WhenCreatingVacancyDetailsViewModel.cs, src/SFA.DAS.FAA.Web.UnitTests/TagHelpers/AccessibleListTagHelperTests.cs, src/SFA.DAS.FAA.Web.UnitTests/TagHelpers/TagHelperOutputExtensions.cs, src/SFA.DAS.FAA.Web/Extensions/AccessibilityExtensions.cs, src/SFA.DAS.FAA.Web/Models/Vacancy/VacancyDetailsViewModel.cs, src/SFA.DAS.FAA.Web/TagHelpers/AccessibleListTagHelper.cs, src/SFA.DAS.FAA.Web/Views/SavedSearches/Unsubscribe.cshtml, src/SFA.DAS.FAA.Web/Views/SearchApprenticeships/Index.cshtml, src/SFA.DAS.FAA.Web/Views/Shared/_SavedSearch.cshtml, src/SFA.DAS.FAA.Web/Views/Vacancies/_ClosedVacancyWhenAuthenticated.cshtml, src/SFA.DAS.FAA.Web/Views/Vacancies/_LiveVacancy.cshtml
Also fixed a bug with the closed vacancy view showing the map:
1. outside the Check Your Travel section
2. when the addresses have no geocode data
=> FAI-2451 Update FAA bullet points code Vacancy page and Applications
